version: '1.0'
stages:
  - stage1
steps:
  build-contracts-and-tests:
    type: build
    image_name: testimagewwe31
    tag: test
    dockerfile:
      content: |
       FROM alpine
       RUN apk add git
          
  run_integration_tests:
      image:  ${{build-contracts-and-tests}}
      #image: alpine
      title: "Running integration tests"
      environment:
          - CONTRACTS_MONGO_DBNAME=contracts
          - CONTRACTS_MONGO_URI=mongodb://mongo
      commands:
        #- bash -c "sbt -Dfile.encoding=UTF-8 -Dsbt.ivy.home=./.ivy2 -mem 4096 test"
        - "sleep 10"
      services:
        composition:
          mongo:
            image: mongo:3.2
            ports:
              - 27017
        setup:
          image: mongo:3.2
          commands:
              - echo in stepup page
              - sleep 10
              - echo end setup
